siteName: Perennial Weaver
author: David White
poweredBy: Kabooly
poweredByUrl: https://kabooly.com
email: perennialweaver@btinternet.com
phoneNumber: "07950172499"
townCity: Twickenham
region: London
postCode: TW1 4HT
locationLatLong: "51.44508074720791, -0.3394408776890249"
country: "GB"
googleOpeningMonday: "09:00"
googleClosingMonday: "17:00"
googleOpeningTuesday: "09:00"
googleClosingTuesday: "17:00"
googleOpeningWednesday: "09:00"
googleClosingWednesday: "17:00"
googleOpeningThursday: "09:00"
googleClosingThursday: "17:00"
googleOpeningFriday: "09:00"
googleClosingFriday: "17:00"
googleOpeningSaturday: "09:00"
googleClosingSaturday: "17:00"
